theme: jekyll-theme-cayman
show_downloads: "true"
github:
  repository_name: "VR Toolkit"
  zip_url: https://github.com/retroluxfilm/reshade-vrtoolkit/releases/download/v0.9.3-pre/VRToolkitReshadeUniversal_0.9.3-pre.zip
logo: /assets/images/vrtoolkit_logo.png
image: /assets/images/vrtoolkit_opengraph.png
